export const BIRTH_REGISTRATION_REQUEST = 'BIRTH_REGISTRATION_REQUEST';
export const BIRTH_REGISTRATION_SUCCESS = 'BIRTH_REGISTRATION_SUCCESS';
export const BIRTH_REGISTRATION_FAIL = 'BIRTH_REGISTRATION_FAIL';
export const BIRTH_REGISTRATION_RESET = 'BIRTH_REGISTRATION_RESET';
