export const CITIZEN_POST_REQUEST = 'CITIZEN_POST_REQUEST';
export const CITIZEN_POST_SUCCESS = 'CITIZEN_POST_SUCCESS';
export const CITIZEN_POST_FAIL = 'CITIZEN_POST_FAIL';
export const CITIZEN_POST_RESET = 'CITIZEN_POST_RESET';

export const CITIZEN_LOGIN_REQUEST = 'CITIZEN_LOGIN_REQUEST';
export const CITIZEN_LOGIN_SUCCESS = 'CITIZEN_LOGIN_SUCCESS';
export const CITIZEN_LOGIN_FAIL = 'CITIZEN_LOGIN_FAIL';
export const CITIZEN_LOGIN_RESET = 'CITIZEN_LOGIN_RESET';
