export const CITIZEN_POST_REQUEST = 'CITIZEN_POST_REQUEST';
export const CITIZEN_POST_SUCCESS = 'CITIZEN_POST_SUCCESS';
export const CITIZEN_POST_FAIL = 'CITIZEN_FETCH_FAIL';
export const CITIZEN_POST_RESET = 'CITIZEN_FETCH_RESET';
