export const COMPLAIN_REGISTRATION_REQUEST = 'COMPLAIN_REGISTRATION_REQUEST';
export const COMPLAIN_REGISTRATION_SUCCESS = 'COMPLAIN_REGISTRATION_SUCCESS';
export const COMPLAIN_REGISTRATION_FAIL = 'COMPLAIN_REGISTRATION_FAIL';
export const COMPLAIN_REGISTRATION_RESET = 'COMPLAIN_REGISTRATION_RESET';
