export const DEATH_REGISTRATION_REQUEST = 'DEATH_REGISTRATION_REQUEST';
export const DEATH_REGISTRATION_SUCCESS = 'DEATH_REGISTRATION_SUCCESS';
export const DEATH_REGISTRATION_FAIL = 'DEATH_REGISTRATION_FAIL';
export const DEATH_REGISTRATION_RESET = 'DEATH_REGISTRATION_RESET';
