export const MARRIAGE_REGISTRATION_REQUEST = 'MARRIAGE_REGISTRATION_REQUEST';
export const MARRIAGE_REGISTRATION_SUCCESS = 'MARRIAGE_REGISTRATION_SUCCESS';
export const MARRIAGE_REGISTRATION_FAIL = 'MARRIAGE_REGISTRATION_FAIL';
export const MARRIAGE_REGISTRATION_RESET = 'MARRIAGE_REGISTRATION_RESET';
