export const NOTICES_FETCH_REQUEST = 'NOTICES_FETCH_REQUEST';
export const NOTICES_FETCH_SUCCESS = 'NOTICES_FETCH_SUCCESS';
export const NOTICES_FETCH_FAIL = 'NOTICES_FETCH_FAIL';

export const ALL_NOTICES_FETCH_REQUEST = 'ALL_NOTICES_FETCH_REQUEST';
export const ALL_NOTICES_FETCH_SUCCESS = 'ALL_NOTICES_FETCH_SUCCESS';
export const ALL_NOTICES_FETCH_FAIL = 'ALL_NOTICES_FETCH_FAIL';
